# Generated by Django 5.0.3 on 2024-03-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="starts",
            new_name="stars",
        ),
    ]
